import type { Metadata } from "next";
import { FontClassNames } from "./Styles/Font";
import "./Styles/GlobalStyles.css";

export const metadata: Metadata = {
  title: "GoodJam",
  description: "Generated by ChanghyeonOh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html>
        <body className={FontClassNames}>{children}</body>
      </html>
    </>
  );
}
